import json

WIN_WIDTH = 1280
WIN_HEIGHT = 720
TILESIZE = 64
FPS = 60

PET_SIZE = 32
PET_SPEED = 1
PLAYER_LAYER = 1
PLAYER_SPEED = 1
SPRINT_MULTIPLIER = 2.0

# Tile visibility: 1 = visible, 2 = invisible
TILES_VISIBLE = 2